/// Built-in list of notoriously weak and common passwords.
pub static COMMON_PASSWORDS: &[&str] = &[
    "123456",
    "12345678",
    "123456789",
    "1234567890",
    "12345",
    "password",
    "1234567",
    "qwerty",
    "1234567890",
    "1234",
    "111111",
    "123123",
    "admin",
    "welcome",
    "login",
    "password123",
    "abc123",
    "secret",
    "p@ssword",
    "pass1234",
    "master",
    "administrator",
    "guest",
    "changeme",
    "iloveyou",
    "sunshine",
    "princess",
    "monkey",
    "dragon",
    "football",
    "shadow",
    "superman",
    "baseball",
    "trustno1",
    "mustang",
    "super123",
    "root",
    "sysadmin",
    "testing",
    "letmein",
    "qwertyuiop",
    "zxcvbnm",
    "abcdef",
    "000000",
    "password1",
    "computer",
    "internet",
];

/// Returns true if `candidate` (case-insensitive) is present in the built-in blocklist.
pub fn is_common_password(candidate: &str) -> bool {
    let lower = candidate.to_lowercase();
    COMMON_PASSWORDS.iter().any(|&common| common == lower)
}
