[package]
name = "password-hasher-bcrypt"
version = "1.0.0"
edition = "2024"
description = "Bcrypt password hasher implementation for the password-hasher crate."

[features]
default = ["async"]
async = ["dep:async-trait", "dep:tokio"]

[dependencies]
async-trait = { version = "0.1", optional = true }
bcrypt = { version = "0.19" }
password-hasher = { path = "../password-hasher" }
tokio = { version = "1.53", features = ["rt", "sync"], optional = true }

[dev-dependencies]
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
