[package]
name = "secret-store-memory"
version = "0.0.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
secret-store = { path = "../secret-store" }
tokio = { version = "1.53", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.53", features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
