[workspace]
resolver = "3"
members = [
    "crates/email-sender",
    "crates/email-sender-memory",
    "crates/email-sender-resend",
    "crates/email-sender-sendgrid",
    "crates/email-sender-smtp",
    "crates/event-sourcing",
    "crates/event-store-memory",
    "crates/event-store-postgres",
    "crates/event-store-umadb",
    "crates/kv-store",
    "crates/kv-store-memory",
    "crates/kv-store-postgres",
    "crates/kv-store-redb",
    "crates/kv-store-redis",
    "crates/password-hasher",
    "crates/password-hasher-argon2",
    "crates/password-hasher-bcrypt",
    "crates/password-hasher-noop",
    "crates/secret-store",
    "crates/secret-store-memory",
    "crates/secret-store-postgres",
]

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

