[workspace]
resolver = "3"
members = [
    "crates/cqrs",
    "crates/email-sender",
    "crates/email-sender-resend",
    "crates/email-sender-sendgrid",
    "crates/email-sender-smtp",
    "crates/event-sourcing",
    "crates/event-store-postgres",
    "crates/event-store-umadb",
    "crates/kv-store",
    "crates/kv-store-postgres",
    "crates/kv-store-redb",
    "crates/kv-store-redis",
    "crates/password-hasher",
    "crates/password-hasher-argon2",
    "crates/password-hasher-bcrypt",
    "crates/secret-store",
    "crates/secret-store-postgres",
    "crates/sms-sender",
    "crates/template-engine",
    "crates/template-engine-askama",
    "crates/template-engine-tera",
    "crates/two-factor-auth",
    "crates/two-factor-auth-backup-code",
    "crates/two-factor-auth-email",
    "crates/two-factor-auth-sms",
    "crates/two-factor-auth-totp",
]

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

