[package]
name = "email-sender-sendgrid"
version = "0.1.0"
edition = "2024"
description = "SendGrid v3 API provider implementation of EmailSender for backend-kit."

[dependencies]
async-trait = "0.1"
email-sender = { path = "../email-sender" }
sendgrid = "0.27"

[dev-dependencies]
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
